Add SkipHelloVerify Option
pion/dtls pull request #513
Opened 2023-01-19 11:10 UTC by xiaokangwang

#### Description
This is a pull request that add SkipHelloVerify option to DTLS library. This is a common behavior for WebRTC Peer on browser stack where DoS resistance on DTLS level is redundant as this is built into ICE.

It have been observed that snowflake, a crowdsourced censorship resistant proxy has been blocked in some part of Russia by identifying the transmission of HelloVerify packet. This pull request is a series of pull request to remove this distinguisher.
#### Reference issue

2023-01-19 22:44 UTC, xiaokangwang commented
I will squash all the commit and fix the metadata link once the content of pull request have passed review, unless requested otherwise.

2023-01-20 14:15 UTC, daenney approved these changes
I'm good with the changes. It's a very small change, there's a test that covers the new behaviour and it didn't break any old tests.

2023-01-31 11:43 UTC, xiaokangwang commented
I have get every check passed. Please have another look, and merge it if possible.

2023-01-31 16:38 UTC, daenney commented
Brilliant, thank you! Things still look fine to me but I'll leave a bit of time for another maintainer, perhaps @at-wat or @stv0g, to have a look at it too. Otherwise I'll merge it end of the week.

2023-02-01 18:35 UTC, stv0g requested changes

2023-02-01 18:35 UTC, stv0g commented on config.go
> +	SkipHelloVerify bool
I would propose the rename the option to InsecureSkipVerifyHello or something along those line, to keep it aligned with tls.Config's InsecureSkipVerify options.

2023-02-03 12:48 UTC, xiaokangwang commented
Hi! I have renamed the new option to InsecureSkipVerifyHello as per request, and rebased it on the most recent primary branch.

2023-02-03 14:44 UTC, merged